development:
  adapter: postgresql
  encoding: unicode
  database: somos_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: somos_test
  pool: 5
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: somos_production
  pool: 5
  host: localhost
